### ISSUE TITLE
Do Not try to obtain handles option?

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#150] opened 2017-01-19 22:33 UTC
Options that do not create handles(processhacker check handle list)

1)obtain handles option on
goto address targetprogram.exe+5125(obregistercallbacks on & off ) -> success
goto address kernel32.sleep ->symbol error(This is not a valid address) ->fail
ctrl+alt+s(Enumetate DLL View) -> Possible -> success!!

2)Is dbvm an openprocess handle absolutely necessary?
(obtain handle on -> handle not create) 
DBVM target process Debug -> Crash Dead

3)Process suspend & resume((Not possible because there is no handle?)

**Comment by kitty8904** [comment] 2017-01-20 00:49
obregistercallbacks protected process  

virtualprotectex fix possible?

procedure TMemoryBrowser.Makepagewritable1Click(Sender: TObject);

VirtualProtectEx(processhandle,pointer(memoryaddress),4096,PAGE_EXECUTE_READWRITE,x);

processhandle-> fix??

=======================================
obregistercallbacks protected process
Do Not Tray To obtain handles Check ON(Handle yes)-> Process Suspend & Resume Success
Do Not Tray To obtain handles UnCheck OFF(Handle no) -> Process Suspend & Resume Fail

**Comment by cheat-engine** [comment] 2017-01-20 01:16
1: Should be fixed

2: You need a valid handle to set the thread context right now. (Perhaps you can use PsSetThreadContext with the thread object)
Although when you use global debug, the handle is not needed (it will get to the thread during context switches)

3: Might be fixed

as for VirtualProtectEx, what is your intention?  To make it writable, or to make it executable ?
If the problem is writing, then execute dbk_writesIgnoreWriteProtection(true)

**Comment by kitty8904** [comment] 2017-01-20 01:51
1. fixed symbol handler success
2.Obregistercallbacks Protected Process & obtain handler Check ON -> DBVM Debugging ->
Program exception (0x80000004) Crash
(DBVM does not seem to work without handles?)
3.Obregistercallbacks Proteted Process -> EX) 459291-push eax -> push ebx fix Error
(dbk_writesIgnoreWriteProtection(true) -> No problem,Normally fixed after option apply
4.suspend&resume commint testing...

**Comment by kitty8904** [comment] 2017-01-20 02:02
maybe obregistercallbacks protected process createthread possible?

alloc(thread,128)
registersymbol(thread)
alloc(value,4)
registersymbol(value)
createthread(thread)
thread:
mov [value],#1000
ret

obregistercallback protected process -> Thread value Fix -> No value Fix

**Comment by cheat-engine** [comment] 2017-01-20 02:13
lua command createAPC(address) might work for you
Keep in mind that the routine executes in 64-bit, even in 32-bit processes.  (so for a 32-bit target you may want to execute _rtlcreateuserthread  (the underscore is important as that'll get you the 64-bit version)

**Comment by kitty8904** [comment] 2017-01-20 02:35
createAPC(addresss)

cheat engine(64bit) -> targetprocess(32bit) -> setAssemblerMode(1) createAPC(address) ->Crash

cheat engine(64bit) ->targetprocess(64bit) -> createAPC(address)->success

Is it impossible to apply to 32-bit target processes?

**Comment by cheat-engine** [comment] 2017-01-20 03:00
This lua script apparently created a functional thread in the target process if it's 32-bit
`
--errorOnLookupFailure(false)

--debug_removeBreakpoint(getAddress('bla'))
--debug_removeBreakpoint(getAddress('bla2'))

--unregisterSymbol('bla')
--unregisterSymbol('bla2')

setAssemblerMode(1)

autoAssemble([[
alloc(bla,4096)
registersymbol(bla)
registersymbol(bla2)

bla:
sub rsp,88
nop
nop
mov rcx,ffffffffffffffff
mov rdx,0
mov r8,0
mov r9,0

mov [rsp+0],rcx
mov [rsp+8],rdx
mov [rsp+10],r8
mov [rsp+18],r9

mov [rsp+20],rdx
mov [rsp+28],rdx

mov rax,bla2
mov [rsp+30],rax
mov [rsp+38],12345678
mov [rsp+40],rdx
mov [rsp+48],rdx

call _rtlCreateUserThread
nop
add rsp,88
ret

bla2:
nop
nop
nop
ret
]])

--debug_setBreakpoint(getAddress('bla'))
--debug_setBreakpoint(getAddress('bla2'))
createAPC(getAddress('bla'))
`

**Comment by kitty8904** [comment] 2017-01-20 03:14
CTRL+L LuaEngine why? 12345678

target32bit_process script crash dead

setAssemblerMode(1)
autoAssemble([[
alloc(bla,4096)
registersymbol(bla)
registersymbol(bla2)

bla:
sub rsp,88
nop
nop
mov rcx,ffffffffffffffff
mov rdx,0
mov r8,0
mov r9,0
mov [rsp+0],rcx
mov [rsp+8],rdx
mov [rsp+10],r8
mov [rsp+18],r9
mov [rsp+20],rdx
mov [rsp+28],rdx
mov rax,bla2
mov [rsp+30],rax
mov [rsp+38],12345678
mov [rsp+40],rdx
mov [rsp+48],rdx
call _rtlCreateUserThread
nop
add rsp,88
ret

bla2:
nop
nop
nop
ret
]])

createAPC(getAddress('bla'))
setAssemblerMode(0)

**Comment by cheat-engine** [comment] 2017-01-20 03:18
12345678 is the parameter given to the running thread, can be anything

the script works for me on the 32-bit tutorial in ce

**Comment by kitty8904** [comment] 2017-01-20 03:26
okay

setAssemblerMode(1)
 autoAssemble([[
 globalalloc(bla,4096)
 globalalloc(bla2,128)
 globalalloc(bla3,4)
bla:
 sub rsp,88
 nop
 nop
 mov rcx,ffffffffffffffff
 mov rdx,0
 mov r8,0
 mov r9,0
 mov [rsp+0],rcx
 mov [rsp+8],rdx
 mov [rsp+10],r8
 mov [rsp+18],r9
 mov [rsp+20],rdx
 mov [rsp+28],rdx
 mov rax,bla2
 mov [rsp+30],rax
 mov [rsp+38],12345678
 mov [rsp+40],rdx
 mov [rsp+48],rdx
 call _rtlCreateUserThread
 nop
 add rsp,88
 ret

bla2:
mov [bla3],1
 ret
 ]])
createAPC(getAddress('bla'))
setAssemblerMode(0)

Cheat engine x32 tutorial-i386.exe program No Error 

Why would other programs thread crash?

**Comment by cheat-engine** [comment] 2017-01-20 03:27
Perhaps the allocated memory is not executable.
Can you debug the other programs with the windows debugger ?

**Comment by kitty8904** [comment] 2017-01-20 03:32
delphi compile File -> No crash dead
C++ compile File -> Crash dead

**Comment by cheat-engine** [comment] 2017-01-20 03:34
your code has

mov [bla3],1
ret

But you're still in 64-bit assembling mode. Addressing in 64-bit is very different than 32-bit, so that will crash

**Comment by kitty8904** [comment] 2017-01-20 03:37
bla2:
ret
dead

C++ Program Crash
Delphi Program No Crash

**Comment by cheat-engine** [comment] 2017-01-20 03:44
I can't reproduce it. Are you on windows XP , 7 or win10?  (I did hear that XP sp3 has some issues with rtlCreateUserThread)

**Comment by kitty8904** [comment] 2017-01-20 03:48
My OS windows7 x64 ultimate
notepad++ x86 Test ->Crash
https://notepad-plus-plus.org/download/v7.3.1.html

**Comment by cheat-engine** [comment] 2017-01-20 04:12
these already crash with
```
setAssemblerMode(1)
autoAssemble([[
alloc(bla,4096)
registersymbol(bla)

bla:
nop
nop
ret

]])

createAPC(getAddress('bla'))
setAssemblerMode(0)
```

so not sure what to do about that (perhaps some kind of protection, or badly coded handlers that don't know that a thread alert can interrupt a sleep state)

But if it's important I guess you can always hook a often executed piece of code and create the thread from there

**Comment by kitty8904** [comment] 2017-01-20 04:19
ntdll.RtlExitUserThread - 8B FF                 - mov edi,edi

ntdll.RtlExitUserThread+33 - 56                    - push esi
ntdll.RtlExitUserThread+34 - E8 B590FCFF           - call ntdll.ZwTerminateThread

ntdll.ZwTerminateThread - B8 50000000           - mov eax,00000050 { 80 }
ntdll.NtTerminateThread+5- 33 C9                 - xor ecx,ecx
ntdll.NtTerminateThread+7- 8D 54 24 04           - lea edx,[esp+04]
ntdll.NtTerminateThread+B- 64 FF 15 C0000000     - call fs:[000000C0]
ntdll.NtTerminateThread+12- 83 C4 04              - add esp,04 { 4 }
ntdll.NtTerminateThread+15- C2 0800               - ret 0008 { 8 }

ntdll.NtTerminateThread -> Crash API routine

I do not know anything more.

**Comment by kitty8904** [comment] 2017-01-20 04:31
https://github.com/DarthTon/Blackbone/blob/74da61b2af50ebd09ac83aa7fa15a356b6ad3a41/src/BlackBoneDrv/Inject.c#L43

https://github.com/DarthTon/Blackbone/blob/74da61b2af50ebd09ac83aa7fa15a356b6ad3a41/src/BlackBoneDrv/Inject.c#L369

KernelMode Inject Thread Code ?

**Comment by cheat-engine** [comment] 2017-01-20 12:16
I've almost copy/pasted the Blackbone code during a test, and the target still crashes

**Comment by kitty8904** [comment] 2017-01-20 12:38
shit...TT 

obregistercallbacks routine bypass possible

but i wondered about debugging, threading, reading and writing protected processes
(handle protect process bypass)

This time I knew that it was not easy to bypass the handle

**Comment by kitty8904** [comment] 2017-01-20 12:49
https://github.com/DarthTon/Xenos/blob/54316465382e0060e0fce8d33d7c4a9fb5aee67f/src/InjectionCore.h#L19

https://github.com/DarthTon/Xenos/blob/54316465382e0060e0fce8d33d7c4a9fb5aee67f/src/InjectionCore.cpp#L691

Xenos injection & BlackBone?
(inject type kernel createthread,kernel apc,kernel manual mapping injection)

**Closed** 2017-05-26 13:26 UTC
