### ISSUE TITLE
Ansi UTF8 UniCode View (Cheatengine 6.5.1 Cheatengine 6.6 beta)

### ISSUE THREAD

**Issue by kitty8904** [cheat-engine/cheat-engine#103] opened 2016-09-09 00:51 UTC
![view](https://cloud.githubusercontent.com/assets/18622105/18371823/6d8c05f8-7672-11e6-8029-7efb45636390.png)
![fix](https://cloud.githubusercontent.com/assets/18622105/18371831/7aca445a-7672-11e6-90b2-e42305c45f27.png)

UniCode Multi Line 한글 input code
5C D5 00 AE 00 00 0A

UniCode single Line 한글 input code Enter
5C D5 00 AE 00 00 00 00 58 00 58
byte trash code?( 00 58 00 58)

compare
5C D5 00 AE 00 00 0A (Multi Line Input)
(Cheat Engine value Double Click Multi Line Box ValueEdit)

5C D5 00 AE 00 00 00 00 58 00 58(Singgle Line Input)
(Cheat Engine value Enter -> No Box Value Fix)

UTF8 & Ansi

ED 95 9C EA B8 80 (UTF 8) value View Error

C7 D1 B1 DB 0D 0A (Ansi ) value View No Error

5C D5 00 AE 00 value View No Error(Unicode)

한글 String value Fix Only UTF8?

Information is modified string as UTF8 

But The string does not display information (UTF 8)

Cheat Engine 6.5.1 -> UTF8 String View No Error

Cheat Engine 6.6 Beta -> UTF8 String Value View Error

**Comment by cheat-engine** [comment] 2016-09-13 22:45
I've come with a 'Solution'.  Not sure if you like it or not, but text is now only UTF-8 or UTF-16 . No support for the native windows codepage. (Impossible for me to bugfix)

**Comment by kitty8904** [comment] 2016-09-13 23:18
![error2](https://cloud.githubusercontent.com/assets/18622105/18494789/8b9a110e-7a53-11e6-8885-54018a2fc0d2.png)

View UTF8 solve the problem , but you're in the same fix UTF16?

multi line input box value edit & singie line input box value edit(cheat engine value enter value fix)

**Comment by cheat-engine** [comment] 2016-09-14 01:10
check now

**Comment by kitty8904** [comment] 2016-09-14 02:03
![error3](https://cloud.githubusercontent.com/assets/18622105/18497627/cf4cff26-7a6a-11e6-9a1d-4540a33c3af0.png)

UTF 8 한글 string search not error fast search

UTF-16 한글 string search slow search and view error
Found : 27,626,391
(big data string result and found list view error => UTF 16)

**Comment by kitty8904** [comment] 2016-09-14 02:26
Features suggests

Latest cheat engine knows to be the font settings

wchar utf8 utf16, can it possibly updated display other language except English utf16 the memory viewer 

Other languages view possible?
(A long ago answer was a dark byte is impossible)

![languages](https://cloud.githubusercontent.com/assets/18622105/18498024/222dce16-7a6e-11e6-8aa6-3a7fe490fba4.png)

**Comment by kitty8904** [comment] 2016-09-14 03:07
![nextscanenglishnobug](https://cloud.githubusercontent.com/assets/18622105/18498724/b475f802-7a73-11e6-96e5-ced618ff5f79.png)

![nextscanbug](https://cloud.githubusercontent.com/assets/18622105/18498734/c1955c6c-7a73-11e6-932a-dc3c50a21f02.png)

next scan search after
utf8,utf16 english no bug

next scan search after 
utf8,utf16 search data string value change next scan search result zero

**Comment by kitty8904** [comment] 2016-09-14 03:48
UTF16 next scan search result solve the problem

![8bit](https://cloud.githubusercontent.com/assets/18622105/18499377/56e1aca8-7a79-11e6-8f34-57a8db3706e0.png)

![16bit](https://cloud.githubusercontent.com/assets/18622105/18499382/5b9caf04-7a79-11e6-8912-26a61802f488.png)

8bit memory view not possible

16bit(UTF16) memory view other languages view possible!(thank you dark byte)

8bit(UTF8) is the view will not?

**Comment by kitty8904** [comment] 2016-09-14 04:12
-reg font save name bug-

![reg](https://cloud.githubusercontent.com/assets/18622105/18499756/d721c486-7a7c-11e6-8848-c51b186f59b2.png)
![reg2](https://cloud.githubusercontent.com/assets/18622105/18499758/dac27df6-7a7c-11e6-9023-9b1604b1c2a7.png)

Set font regedit & text Preferences Reg_SZ value English Ms sans Serif Not Error

But Korea 돋움Font => ?뗭? error Font Data Save

**Comment by cheat-engine** [comment] 2016-09-14 20:23
I'll look into the font saving (does it load it back properly or is that bugged as well? in case it's just a regedit display issue ) and perhaps the UTF8 char thing, but due to the variable size of UTF8 I don't see it as an default enabled option.  (the way UTF8 can be encoded it can mess up regular ascii strings if the preceding bytes say something else)

as for the comment part, no, not possible.
The comment part is based on the autoguess algorithm, and the guess routine would never recognize  EA9C95ED as a valid string. At most a number, of pointer.

**Comment by kitty8904** [comment] 2016-09-14 21:23
1. UTF 16 View success UTF 8 View not view
UTF16(unicode) = memory view hex view possible decode

UTF8 Japanese,korean,Chinese 3byte = 1 text string

ED 95 9C = 한
EA B8 80 = 글

UTF8 Memory View hex view string not decode (Impossible?)

=================================================================
2.
comment impossible ok

=====================================

3.font name save data disassemblerview,hexview,override the default font

font name not english => regedit font name crash data save

font name  english => regedit font name not bug

**Comment by kitty8904** [comment] 2016-09-15 18:57
**Memory View String Decode solve the problem**

UTF8,UTF16 hex view possible (dark byte thank you)
(ascii encoding is supported basic English View?)

FontLoad small bug

Hexview  English Font Name(Consolas,Courier New) -> cheat engine exit -> cheat engine run 
-> font data load success

Hexview Not English Font Name(굴림체,궁서체) ->cheat engine exit -> cheat engine run
-> font data default font (Courier New Font Load)

**Comment by cheat-engine** [comment] 2016-09-15 18:57
3: If you select such a font, apply it, and then open the font change window. Will it show the correct name, or the wrong one ?

**Comment by kitty8904** [comment] 2016-09-15 18:59
English font Load & Display View Not Error

No English font Load => regedit regdata DisPlay View string crash 

default Font Data Load(Courier New)

**Comment by cheat-engine** [comment] 2016-09-15 19:30
what I mean, is if you open the font change window, after having changed the font to 궁서체 , and then open the font change window again (without closing cheat engine), will it show the correct name in the dialog that pops up ?

**Comment by kitty8904** [comment] 2016-09-15 19:48
wait dark byte video record

**Comment by kitty8904** [comment] 2016-09-15 20:02
https://youtu.be/vUci96kRSPs

**Comment by cheat-engine** [comment] 2016-09-15 20:02
I know regedit will show a different string, it's a different encoding style, but i'm more curious if it goes wrong before saving

**Comment by kitty8904** [comment] 2016-09-15 20:04
By first selecting a font is not a problem when loading

but reload font error(no english font)

**Comment by cheat-engine** [comment] 2016-09-16 00:16
I can not reproduce this (I can't find fonts with a foreign fontname, they all end up english) so I can't fix it.

perhaps you can do some testing/debugging at https://github.com/cheat-engine/cheat-engine/blob/master/Cheat%20Engine/fontSaveLoadRegistry.pas

**Comment by kitty8904** [comment] 2016-09-16 00:54
fixed Reg.WriteString

line 29
reg.WriteString('Name', WinCPToUTF8(fd.Name)); => reg.WriteString('Name', UTF8ToWinCP(fd.Name));

FontName 궁서체 Write Save Success but read 궁서체 Font Load error

**Comment by kitty8904** [comment] 2016-09-16 01:43
MemoryBrowserFormUnit.pas
procedure TMemoryBrowser.miTextPreferencesClick(Sender: TObject);
var
  x: TfrmMemviewPreferences;
  i: TDisassemblerViewColorsState;
  reg: tregistry;
  fd: TFontData;
begin
  with TfrmMemviewPreferences.create(self) do
  begin
    fd:=Graphics.GetFontData(disassemblerview.font.handle);
    fontdialog1.font.Name:=fd.Name;
    fontdialog1.font.height:=fd.height;
    fontdialog1.font.Pitch:=fd.Pitch;
    fontdialog1.font.Style:=fd.Style;
    fontdialog1.font.CharSet:=fd.CharSet;
    fontdialog1.font.Quality:=fd.Quality;
    fontdialog1.font.Orientation:=fd.Orientation;

    btnFont.Caption:=fontdialog1.Font.Name+' '+inttostr(fontdialog1.Font.Size);

    //FontDialog2.Font.Assign(hexview.HexFont);
    fd:=Graphics.GetFontData(hexview.HexFont.handle);
    fontdialog2.font.Name:=fd.Name;
    fontdialog2.font.height:=fd.height;
    fontdialog2.font.Pitch:=fd.Pitch;
    fontdialog2.font.Style:=fd.Style;
    fontdialog2.font.CharSet:=fd.CharSet;
    fontdialog2.font.Quality:=fd.Quality;
    fontdialog2.font.Orientation:=fd.Orientation;

    **btnHexFont.Caption:=fontdialog2.Font.Name+' '+inttostr(fontdialog2.Font.Size);**

View ->Text Perference -> Add btnHexFont Caption Font Data

**Comment by kitty8904** [comment] 2016-09-16 10:14
fontsaveloadregistry 
line 37 delete
//s: string;

**Closed** 2016-11-04 12:04 UTC
