### ISSUE TITLE
Cheat Engine 7.0 new incorrect work

### ISSUE THREAD

**Issue by Atamg1994** [cheat-engine/cheat-engine#964] opened 2019-11-09 10:41 UTC
7.0 does not activate scripts
can't find byte array

6.8.3 work fine again and the question arises

 either update all non-working cheats to 7.0

either store multiple versions on pc ...
![Screenshot_21](https://user-images.githubusercontent.com/57526178/68527318-3dc4c880-02ee-11ea-8ab1-55dd854543c3.png)
![Screenshot_22](https://user-images.githubusercontent.com/57526178/68527321-44534000-02ee-11ea-8956-d7e06bf5d42b.png)

**Comment by Atamg1994** [comment] 2019-11-09 10:49
I do not like to cheat
even so I like to do something like mods
for example: regeneration hp based on the player parameters, or the ability of a vampire - when killing a part of an HP player.


and since version 7.0 is not correct work, it’s a little difficult to make such mods

I strongly wish that your project develops and therefore decided to show possible errors, and I hope you will fix them in future versions

**Comment by Atamg1994** [comment] 2019-11-09 11:04
![Screenshot_23](https://user-images.githubusercontent.com/57526178/68527568-ed029f00-02f0-11ea-81ed-7762340dac43.png)


 7,0 disassemble new instruction 

by the way! If you simultaneously connect two versions to the game, then everything works fine
 which leads to one clarification - in 7.0 there are still errors in the work

**Comment by mgrinzPlayer** [comment] 2019-11-09 11:53
Could you try this CE binary. I know that it's name contains 'WinXP', that's because official 32bitCE7.0 doesn't work on WinXP (CE compiled with FPC3.2.0). This binary is compiled with FPC3.0.4:
https://www19.zippyshare.com/v/urrzB6hd/file.html

**Comment by Atamg1994** [comment] 2019-11-09 12:07
> Не могли бы вы попробовать этот двоичный файл CE. Я знаю, что это имя содержит «WinXP», потому что официальный 32bitCE7.0 не работает на WinXP (CE скомпилирован с FPC3.2.0). Этот двоичный файл скомпилирован с FPC3.0.4:
> https://www19.zippyshare.com/v/urrzB6hd/file.html

i use windows 10 64bit

**Comment by Atamg1994** [comment] 2019-11-09 12:11
here's what else noticed if you connect the debugger
and manually find the instructions then it starts to work ... and now I’ll record a script for the video) I’ll throw off the reference

**Comment by mgrinzPlayer** [comment] 2019-11-09 12:18
ignore the 'WinXP', just try this binary.

**Comment by Atamg1994** [comment] 2019-11-09 12:28
tried also does not work.
only works as on video

https://youtu.be/UT79_rgonBY

**Comment by Atamg1994** [comment] 2019-11-09 12:30
> игнорируйте 'WinXP', просто попробуйте этот двоичный файл.

пробовал и не работает.
работает только как на видео

https://youtu.be/UT79_rgonBY

**Comment by Atamg1994** [comment] 2019-11-09 13:00
I think you have a problem with the availability of memory regions
they say he does not see etu memory and tdp
after searching manually starts to see


which leads to the idea that the first problem I wrote about is that it’s not known why
7 version uses 14 byte jumps
- where 6,8,3 on the same example uses normal

and so, most likely, an error somewhere in the forgiveness of the region of memory and because of this the wrong size of the region, and therefore, when injecting, the memory is allocated further than it should be

**Comment by Atamg1994** [comment] 2019-11-09 13:16
I wanted to use 6.8.3 but there the veh debuger does not work correctly on the 64bit version

**Comment by cheat-engine** [comment] 2019-11-09 14:24
Check out the script to see why it fails to activate , which aob result fails

e.g you ran a previous table, didn't disable it or the disable used the wrong bytes then re-enable will fail because the bytes are not what it expects 

also if the aob is on a pageboundary and the editing happens in only one part, rhen the scanner may not find them as the two regions are different classifications then

**Comment by Atamg1994** [comment] 2019-11-09 14:28
> Check out the script to see why it fails to activate , which aob result fails
> 
> e.g you ran a previous table, didn't disable it or the disable used the wrong bytes then re-enable will fail because the bytes are not what it expects
> 
> also if the aob is on a pageboundary and the editing happens in only one part, rhen the scanner may not find them as the two regions are different classifications then


sorry once again
the problem was solved by itself after rebooting the pc (with the installation of updates)
- 7.0 works .... Sorry for wasting your time

**Comment by Atamg1994** [comment] 2019-11-09 15:23
again does not work ....

**Comment by Atamg1994** [comment] 2019-11-09 15:25
> Check out the script to see why it fails to activate , which aob result fails
> 
> e.g you ran a previous table, didn't disable it or the disable used the wrong bytes then re-enable will fail because the bytes are not what it expects
> 
> also if the aob is on a pageboundary and the editing happens in only one part, rhen the scanner may not find them as the two regions are different classifications then

not working again
everything is ok from the scripts .. there are no other running versions .. the problem is in version 7.0

 since 6.8.3 works perfectly

**Comment by Atamg1994** [comment] 2019-11-09 15:27
> Check out the script to see why it fails to activate , which aob result fails
> 
> e.g you ran a previous table, didn't disable it or the disable used the wrong bytes then re-enable will fail because the bytes are not what it expects
> 
> also if the aob is on a pageboundary and the editing happens in only one part, rhen the scanner may not find them as the two regions are different classifications then


check the table yourself 
[mb_warband.zip](https://github.com/cheat-engine/cheat-engine/files/3827430/mb_warband.zip)

**Comment by Atamg1994** [comment] 2019-11-09 17:14
> Check out the script to see why it fails to activate , which aob result fails
> 
> e.g you ran a previous table, didn't disable it or the disable used the wrong bytes then re-enable will fail because the bytes are not what it expects
> 
> also if the aob is on a pageboundary and the editing happens in only one part, rhen the scanner may not find them as the two regions are different classifications then

earned again ...


again with jumps a little problem

see video https://youtu.be/vrXTqqfifXk

**Comment by mgrinzPlayer** [comment] 2019-11-09 18:25
I can confirm that "jmp short +XX" is broken.

![obraz](https://user-images.githubusercontent.com/9157726/68533267-9dd76100-0326-11ea-8048-817f10ed62ee.png)

**Comment by cheat-engine** [comment] 2019-11-09 18:26
Next time it fails again, replace the `aobscanmodule(FullMap,mb_warband.exe,80 ? E9 06 00 00 00 75 0D F7 41)` with `aobscan(FullMap,80 ** E9 06 00 00 00 75 0D F7 41)`

and do a full aob scan in CE for 80 ** E9 06 00 00 00 75 0D F7 41 with all 3 memory type options set to gray, see if that finds something
And once you've found the memory using the disassembler, go to memoryview->view memory regions, and find the region it's in and get a screenshot of that region and the ones around it.

Also, make sure there is nothing checked in settings->extra

I'll fix the jmp short

**Comment by Atamg1994** [comment] 2019-11-09 21:09
> Also, make sure there is nothing checked in settings->extra

disabling settings->extra helped the problem was solved))   Thank you so much

**Closed** 2019-11-09 21:11 UTC
