### ISSUE TITLE
UI Bug: Missing Borders

### ISSUE THREAD

**Issue by dsasmblr** [cheat-engine/cheat-engine#380] opened 2018-07-02 22:24 UTC
All windows in CE appear to be missing the right (and possibly bottom) border. See below:

![ui-bug](https://user-images.githubusercontent.com/22781064/42189183-2281329c-7e25-11e8-99f7-99a802267286.png)

**Comment by dsasmblr** [comment] 2018-07-13 04:06
Another UI bug, this time with when selecting "Binary" as your Value Type:

![binary-search](https://user-images.githubusercontent.com/22781064/42671876-77f1cdb4-8630-11e8-8d4e-6bd51fece2e0.png)

**Comment by dsasmblr** [comment] 2018-10-02 17:14
The border is apparently a Windows 10 issue as it's happening with other programs; however, the inconsistencies like the Binary search still apply. I'll close this issue if that's something that's been sorted.

**Comment by felubra** [comment] 2018-10-07 01:57
Could not reproduce on my system.

![image](https://user-images.githubusercontent.com/25326257/46577163-0468ad80-c9b6-11e8-9d1a-62e4db3feeb6.png)
![image](https://user-images.githubusercontent.com/25326257/46577142-9f14bc80-c9b5-11e8-9973-d81ecaee9a79.png)

I suspect the border problem is related with bugs in the scaling engine on Windows 10 prior to version 1703. I had issues with this in the past - an extra white line and blurry elements. They [improved](https://blogs.windows.com/buildingapps/2017/04/04/high-dpi-scaling-improvements-desktop-applications-windows-10-creators-update/#xKbCi3Vs5gR62IOS.97) the engine after the 1703 but I made this assumption not knowing your version. Could you try to verify if this is the case?

**Comment by cheat-engine** [comment] 2018-10-07 08:06
As for the stuff like bits and decimal being too far to the left that's a bug yes (though difficult to fix)

**Comment by cheat-engine** [comment] 2018-12-12 13:43
should be fixed now (in a silly way)

**Closed** 2019-07-23 21:33 UTC
Labels: Fixed but needs checking
