### ISSUE TITLE
Add a free license

### ISSUE THREAD

**Issue by pizzamaker** [cheat-engine/cheat-engine#60] opened 2016-03-07 22:53 UTC
This repo seems to be lacking a free license. I suggest AGPLv3+.

**Comment by mylemans** [comment] 2016-03-17 13:56
Why AGPLv3 @pizzamaker ?

**Comment by pizzamaker** [comment] 2016-03-17 22:12
The Affero GPL has all the goodies of the GPL (ensuring no one can privatize your work), as well as closing the SaaSS loophole: basically if someone turns your engine into an online app (believe me, it's possible nowadays), they will need to redistribute the source as well.

**Comment by mylemans** [comment] 2016-03-18 06:51
Well, I'm more for a true open license world, so my vote would go to a BSD or MIT license.

**Comment by pizzamaker** [comment] 2016-03-18 20:27
Well, at the end of the day, any free software license is better than none :)

**Comment by valerio-bozzolan** [comment] 2017-04-12 22:28
...so? :)

**Comment by C0rn3j** [comment] 2017-04-28 15:33
> as well as closing the SaaSS loophole: basically if someone turns your engine into an online app (believe me, it's possible nowadays)

What's the issue exactly and how does GPLv3 not solve it?

I too am for an open license.

**Comment by valerio-bozzolan** [comment] 2017-04-28 15:36
@C0rn3j The issue is that the author should choose a license :) He/she have to choose the GNU AGPL v3+ / GNU GPLv3+ to be a master of copyleft, or the MIT/BSD for other "WTFPL-like" licenses.

**Comment by C0rn3j** [comment] 2017-04-28 15:39
I was just wondering why you're pushing for AGPLv3 as opposed to GPLv3.

**Comment by valerio-bozzolan** [comment] 2017-04-28 15:43
@C0rn3j ("You" in the sense of I?) See the GNU AGPL as a suitable for a copyleft server software. The GNU GPL is suitable for a copyleft software. The MIT/BSD/WTFPL/Apache are suitable for don't care software.

**Comment by C0rn3j** [comment] 2017-04-28 15:51
@valerio-bozzolan Ah, I've mistaken you for @pizzamaker there. Thanks for explaining the difference, I also found a gnu.org article about it [here](https://www.gnu.org/licenses/why-affero-gpl.en.html).

**Comment by AntumDeluge** [comment] 2019-02-25 20:57
I agree that the repo should have license information. Cheat Engine appears to have its own custom license (found in the installer executable). I'm not sure if it applies to the source code though. I haven't found any license info in the source repo.

This is the text from the *License.txt* file found in the installer executable (*installCore Terms of Service* not included):
```1) This license agreement is a legal agreement between you and the author of this program.
2) By installing or otherwise using this program you agree to be bound by this agreement. If you do not agree to the terms of this Agreement, you may not install or use this program.
3) This program is distributed as "FREEWARE" and "AS IS".
4) The author specifically disclaims all warranties, expressed or implied. In no event shall the author be liable for any damage either from the direct use of this product or as a consequence of the use of this product.
5) By using this software you agree to the possibility of losing access to online services, paid or not, and regardles of if you're running this software and said services at the same time or not
6) You may not use this program in actions, which infringe any law of your country or international laws.
7) You may not use this program in actions, which infringe the rights of any person or entity.
8) You may not use this program in a game, in which you win (earn) real money or things.
9) You may not use this program or any components, to circumvent DRM or other copyright protections
10) You may not use any part of this program or any derivative of it for mallicious purpose
11) You may install and use an unlimited number of copies of this edition of the program on your computers.
12) You may give this program to your friends and other people, but only in the original archive. Original Archive is defined as this installer. Which means it is allowed to be redistributed inside another installer, as long as it goes through the original installer.
13) You may release this edition of the program on CD/DVD/Internet (or other media), but only in the original archive and if this CD is the programs collection.
14) You may upload this edition of the program to your internet website, but only with the original archive present and this website must be with free access for users.
15) You may disassemble and reverse engineer any part of this program, although just looking at the sourcecode is easier 
16) You may not rent, lease or sell this program.```

**Comment by remizovm** [comment] 2019-02-25 21:06
Agreed, this is very important. My choice: MIT.

**Comment by cheat-engine** [comment] 2019-02-26 06:49
I need a license that:
allows use of this sourcecode for private purpose only, without allowing spread to the public. (no public bastardized CE builds/ports, like UCE's, but you're free to make them for yourself)

Also disallow selling of CE binaries, with the exception when packaged inside a trainer generated by CE (That means Tiny and Gigantic trainers can be sold if you wish)
Tables generated by CE are the full ownership of the person who created it  (like the perl license) so can also be sold

So not one of the default licenses

**Comment by valerio-bozzolan** [comment] 2019-02-26 07:31
So if you want restrictions you will not adopt any free as in freedom license.

Please close this bug.

**Comment by C0rn3j** [comment] 2019-04-05 23:16
> Source code is always allowed to be shared

> Tables generated by CE are the full ownership of the person who created it (like the perl license) so can also be sold

I don't think you need to do something specific for those two, so check.

> Allow use of this source code for private purpose only, without allowing spread of binaries to the public. 

> Disallow selling of CE binaries

**Comment by flarn2006** [comment] 2020-09-19 03:29
> I need a license that:
> allows use of this sourcecode for private purpose only, without allowing spread of binaries to the public. (no public bastardized CE builds/ports, like UCE's, but you're free to make them for yourself and a handful of friends, but not a full website dedicated to your CE build/branch)
> ((Sourcecode is always allowed to be shared))
> 
> Also disallow selling of CE binaries, with the exception when packaged inside a trainer generated by CE (That means Tiny and Gigantic trainers can be sold if you wish)
> Tables generated by CE are the full ownership of the person who created it (like the perl license) so can also be sold
> 
> So not one of the default licenses

If those are your only requirements, I'd say your current license is still unnecessarily restrictive.

Also, I could have sworn CE was licensed under a free license at one point. Wikipedia says it's LGPL; is that just outdated or has it always been false? (I'd correct it but I'm not sure what exactly to put there.)

**Comment by megapro17** [comment] 2021-10-12 23:34
> allows use of this sourcecode for private purpose only, without allowing spread of binaries to the public. (no public bastardized CE builds/ports, like UCE's, but you're free to make them for yourself and a handful of friends, but not a full website dedicated to your CE build/branch)

Your requirements are complete bullshit and against of principles of open source software

**Comment by Veratyr** [comment] 2021-11-06 10:22
@cheat-engine you can't use any other Licence rather than GPL-compatible, because Cheat Engine already contains GPL-licensed code. It automatically makes all Cheat Engine code GPL licensed.

**Comment by ThisGitHubUsernameWasAvailable** [comment] 2021-11-06 10:22
@cheat-engine you can't use any other Licence rather than GPL-compatible, because Cheat Engine already contains GPL-licensed code. It automatically makes all Cheat Engine code GPL licensed.

**Comment by cheat-engine** [comment] 2021-11-06 10:42
libtcc is lgpl, not gpl
the synhighlighter files are mpl but are allowed to be used in gpl projects

**Comment by ThisGitHubUsernameWasAvailable** [comment] 2021-11-06 10:48
https://github.com/cheat-engine/cheat-engine/blob/8bdb7f28a9d40ccaa6f4116b13c570907ce9ee2e/Cheat%20Engine/bin/languages/it_IT/LICENSE.MD

**Comment by cheat-engine** [comment] 2021-11-06 10:53
That's lgpl

**Comment by C0rn3j** [comment] 2021-11-06 11:44
Looking at your requirements from [this comment](https://github.com/cheat-engine/cheat-engine/issues/60#issuecomment-467317576) with fresh eyes, I think I found a solution.

I think dual-licensing CE would work, provided you slightly change your mind about some of the requirements.

*  Allows use of this sourcecode for private purpose only, without allowing spread of binaries to the public. _(no public bastardized CE builds/ports, like UCE's, but you're free to make them for yourself and a handful of friends, but not a full website dedicated to your CE build/branch)_
   * People who want to illegally distribute closed-source binaries are unfortunately already doing so, just like UCE which you mentioned
   * Having a copyleft license means they _should_ at least provide the source code, so users aren't running magic binaries
* Disallow selling of CE binaries
  * If the license is copyleft, selling of CE-based binaries would be allowed, but would have to be accompanied by source code, and with the nature of copyleft licensing, person purchasing the binary would have rights to the binary and code allowing them to legally and practically redistribute the fork, making selling it not be an effective approach, as people can just share what they bought for free, legally.
  * Of course, if someone wanted to sell CE-based binaries without providing source code, they are already doing so.
* Allow selling CE binaries when packaged inside a trainer generated by CE _(That means Tiny and Gigantic trainers can be sold if you wish)_
* Tables generated by CE are the full ownership of the person who created it (like the perl license) so can also be sold
  * The trainer binaries are where things get tricky, since with copyleft, creators would have to also provide code and redistribution rights for the binaries which I as far as I understand is something you want to avoid
  * I think the solution to this is aforementioned of dual-licensing CE. One copyleft license, and another license (or an exception part to the copyleft one) that states generated trainers belong to their author and the copyleft license does not inherently apply to them
  * A copyleft license would allow tables to be sold without an issue. Of course, users can share their bought tables for free, but that's what is already happening. But to actually give authors rights over their work, they need to be part of the above exception
* Sourcecode is always allowed to be shared
  * I think the approach I suggest accomplishes this

One additional benefit of licensing your work as copyleft is also that the project does not die with you.

Currently, CE is effectively distributed as All Rights Reserved, which does not legally allow someone to pick your work up when the need arises.

No matter if the license remains All Rights Reserved or changes to something else, thank you for having the code be open source even though it allows for things you explicitly disagree with.

**Comment by ThisGitHubUsernameWasAvailable** [comment] 2021-11-06 12:36
Honestly i don't see any reason why you don't want to use non-restrictive open source licence. Yes, there are some folks who doing something what you don't like. They have always been there and they always will be there regardless of licence. Lack of open source licence does nothing against that, but it harms all other users with good intentions.

**Comment by Gregaras** [comment] 2022-01-21 14:36
I would suggest either LGPL or GPL:
* I believe development of Cheat Engine continued even If original maintainers wouldn't be able to contribute to it anymore
* GNU General Public License would protect Cheat Engine from being licensed under a proprietary software license

You make some people look for an alternative and there is one, which is [PINCE](https://github.com/korcankaraokcu/PINCE).

**Comment by eirnym** [comment] 2022-01-29 21:48
@cheat-engine could you please put the exact license to a file?

**Comment by eirnym** [comment] 2022-01-29 21:57
FYI folks, there's currently **FearlessRevolution "Secure Cheat Engine" (based on CE 7.0)** is published in the internet  and it requires a payment to basically use it. Yes. it isn't the main functionality, only for downloading the cheats, but there's a fact of 1) separate binary pushed 2) based on non-fresh CE 3) built only for Windows. 

I believe, if it'll be an official fork, it would be built on top of the official release, have functionality for Linux and macOS as an official client do, and probably will be a comment on the official page. 

@cheat-engine I believe they steal this way your work if you wasn't agreed on this privately with them.

**Comment by fade2gray** [comment] 2022-01-30 00:02
@eirnym Have you never click on this in the repo's `README.md` ?

![links](https://user-images.githubusercontent.com/1332009/151681651-33871460-2638-4600-8841-11e6e0641b39.png)

**Comment by cheat-engine** [comment] 2022-01-30 12:20
My official stance: I don't support the use of CE's sourcecode in this way

**Comment by flarn2006** [comment] 2022-02-02 03:39
Is that a reply to @eirnym or @fade2gray?

Also, if your goal is only to prohibit people from using the software in ways you don't approve of, then what is the purpose of this part of the license?

> 6) You may not use this program in actions, which infringe any law of your country or international laws.

It seems normal enough, but really all that this clause does is give various third parties (governments) carte blanche to add on additional license restrictions that you won't necessarily agree with. For example, do you really want to make your Chinese users agree, as a condition of using Cheat Engine, that they won't use it for the purpose of evading oppressive government censorship and/or surveillance? Because this is something you are currently doing, whether you intend to or not. Yes, a license violation would surely be the least of their worries if they were to get caught, but regardless, why make your users agree not to do things that, if you had your way, would be legal? (If I assumed wrong and you actually support China's censorship and surveillance, I'm sure you can think of another example that would work.)

Even when it actually is something that you agree your users shouldn't do, the "your country" part means these restrictions will apply unequally to your users, based solely on where they live, a distinction I suspect (correct me if I'm wrong) is wholly irrelevant to their use of the software or to what you personally want to allow or disallow. Case in point: European law allows reverse engineering of software even if the copyright owners seek to prohibit it. Would you, personally, have any moral issues with someone using Cheat Engine to reverse engineer software against the wishes of the copyright owner, enough that you'd want to put a stop to it? Whatever your answer, I sincerely doubt the user's physical location is of any importance to your preference.

If you're only worried about being held liable for users using your software for illegal purposes, I doubt you'd have anything to worry about. IANAL, but free software licenses (by definition) don't contain any clause of the sort, and I've never heard of any issues arising as a result.

**Comment by fade2gray** [comment] 2022-02-02 11:45
@flarn2006 The comment I made was irrelevant and has been removed – so, no, the reply was not directed at me.

**Closed** 2022-04-19 17:42 UTC
