### ISSUE TITLE
Bookmarks in memory view lead to wrong address

### ISSUE THREAD

**Issue by ghost** [cheat-engine/cheat-engine#242] opened 2017-11-01 05:13 UTC
I'm not sure if this is an actual issue, or maybe I didn't properly configure something in settings. Anyway, it seems like it shouldn't behave like it currently behaves.

### The issue

In some processes, bookmarks in memory view will lead to wrong address.

### How to reproduce

Again, the example is Chrome. These are the steps:

1. Open Google Chrome 62.0.3202.75 (Official Build) (64-bit) (cohort: 62_75_win)
2. In Cheat Engine open the main chrome.exe process (or select Chrome's window)
3. Navigate to code address `0x7FFBA2981908`
4. It is permanent address, so you should land at `chrome.IsSandboxedProcess+703204`
5. Bookmark that address
6. Navigate to that bookmark
7. It will navigate you to wrong address (unallocated memory block)

### Screencast

You can see how it looks [here](https://github.com/the-pirate-bay/test/blob/master/1.mp4?raw=true)

**Comment by advanceddeveloper** [comment] 2018-05-04 22:14
@cheat-engine 

It is more than 6 months from posting this issue and it is still reproducible. I would like to help resolve this as much as I can, but can you please let me know what is the hindrance for resolving this issue? Is it unconfirmed, or is it confirmed but hard to fix, or is it fixed, or what?

Thanks.

**Comment by cheat-engine** [comment] 2018-05-05 07:36
I can not reproduce it. it goes to the proper chrome.IsSandboxedProcess and chrome_child.IsSandboxedProcess respectively depending on which one you choose.

When you look at the context menu, what is the address associated with the bookmark Is it all hexadecimal, is is a modulename.dll+offset, or is is a modulename.symbol+offset ?

**Comment by advanceddeveloper** [comment] 2018-05-05 10:14
I've noticed that the previous screen recording I posted is no longer accesible, so I'm providing a new one.

Here I am using Chrome 64bit version 63.0.3239.132 and address `0x7FFBD2EC5B6B`.

[Screen recording](https://www.youtube.com/watch?v=-yxIfu0hID4)

**Comment by cheat-engine** [comment] 2018-05-05 10:49
I still can not reproduce it. Try it in another application that is not chrome (I do not have that version, and 0x7FFBD2EC5B6B is uninitialized memory)
what you can try is disable view->show symbols and see if it makes a difference

**Comment by advanceddeveloper** [comment] 2018-05-05 17:46
@cheat-engine 

> Try it in another application that is not chrome

I couldn't reproduce it in any other application. I think that Chrome probably uses some advanced memory management techniques which CE doesn't expect an application to use.

> I do not have that version of chrome

There are only few addresses in whole Chrome process which shows this weird behavior. I'm not exploring Chrome latest version yet, but I explored all versions from `62.0.3202.75` to `63.0.3239.132` and I made a list of addresses which leads to wrong address when bookmarked. For the current Chrome version I didn't make any researches yet.

Is it possible for you to download Chrome 63.0.3239.132 and install it (you can do it in a virtual machine if you don't want to uninstall your actual version) and check if you can reproduce it? I mean, the only way to reproduce is to check with the given application and given version.

> and using the symbolnames gets me working results

not sure what do you mean....

> what you can try is disable view->show symbols and see if it makes a difference

I didn't notice any difference.

**Comment by advanceddeveloper** [comment] 2018-05-15 04:53
Ping @cheat-engine 

Sorry for me being annoying, but it is more than 10 days from last activity here and I couldn't find any workaround. It is impossible for me to disassemble Chrome processes while this issue is happening. I did my best to look at the CheatEngine source code, but I couldn't understand it in the sense that I would be able to solve the problem myself.

I will do my best to help you and your team (and anyone who is familiar with CheatEngine source code) to work on resolving this issue. In the meanwhile, I tested with Windows 10, Windows 8.1, Windows 7 (both 32bit and 64bit) and also Windows xp (both 32bit and 64bit) and the issue is reproducible with Chrome 63.0.3239.132 on all these platforms.

Do I need to post screen recording for all these platforms? If you need a virtual machine in order to reproduce it (if you don't want to uninstall your Chrome latest version or don't want to mess your files), I can provide you with any virtual machine simulator you like (if you want serial keys for VMWare Workstation Pro I can give it to you), or you can use some free software like Oracle VirtualBox, and if you need Windows xp, 7, 8.1 or 10 iso image file, I can also send it to you. Please tell me what is needed for reproducing this. I mean, currently I cannot make any progress in disassembling Chrome.

My goal is to make automatic program for disabling Chrome's message "Press F11 to exit full screen", which seems to be possible only by modifying Chrome's binaries. In ordre to achive it, I spent more than two years on disassembling and investigating different Chrome versions and now I stuck at this issue and can't make any further progress.

I would be happy to hear from you that you confirm the issue and let me know how hard it would be to fix this issue. If it is a trivial fix, then it is awesome, otherwise I would like to help on resolving this issue.

**Comment by cheat-engine** [comment] 2018-05-15 08:10
disable view->show module addresses and see if that makes a difference

**Comment by advanceddeveloper** [comment] 2018-05-16 04:53
@cheat-engine 

Disabled both `view->show symbols` and `view->show module addresses` and the issue is still present.
Please take a look at the new video: https://www.youtube.com/watch?v=r7KqWZMsmME
I can't see why is it that hard for you to try to reproduce it using the given Chrome version?

> Also, if you want to automate things, I recommend lua instead of gui objects

No, I'm using CheatEngine just to investigate Chrome binaries in order to find out how their routines work. Once I understand the concept behind displaying the message, I will create automaded program in C++ (not in lua) to do the needed assembly modifications (or even better I would modify `chrome.dll` directly, without injecting anything at the runtime).

**Comment by cheat-engine** [comment] 2018-05-16 08:25
can you make that video with symbols and module addresses disabled  ? When both are turned off 'set bookmark' records the address as a hexadecimal string. There should be no symbol lookup confusion then unless something else is messing up

what you can try is delete autorun/luasymbols.pas or replace it with https://github.com/cheat-engine/cheat-engine/blob/master/Cheat%20Engine/bin/autorun/luasymbols.lua

**Comment by advanceddeveloper** [comment] 2018-05-22 17:32
@cheat-engine 

I've succeed to reproduce the issue using the latest Chrome version 66.0.3359.181 both x32 and x64 using windows 7, 8.1 and 10. Here is the video on how to reproduce it with the latest Chrome version: https://www.youtube.com/watch?v=W14NeSzbMrM

The fact that I've found a workaround (disable module names, then bookmark the address, then enable names again) doesn't mean the issue is resolved. Can you please confirm the issue using the latest Cheat Engine and the latest Chrome version following the steps mentioned in the video? Once you confirm the issue, we can see what we can do about it.

Many thanks for your cooperation on this. I hope we will successfully resolve this soon.

**Comment by cheat-engine** [comment] 2018-05-22 18:45
with just show symbols off instead of modulenames off it should work just as well
the problem is that chrome has a chrome.exe with GetHandleVerifier and a chrome.dll with GetHandleVerifier 

The symbollookup system doesn't currently support extension filtering, and disabling symbol bookmarks altogether is not an option, as in normal applications this is very useful

what you can do is place this code in the autorun folder in the ce install folder (name it nosymbolbookmarks.lua or something)
```
mv=GetMemoryViewForm()

if oldbmf==nil then
  oldbmf=mv.miSetBookmark0.OnClick
end

function nosymbolbookmark(s)
  local oldstate=mv.Showsymbols1.Checked
  if oldstate then
    mv.Showsymbols1.DoClick()
  end

  oldbmf(s)

  if oldstate then
    mv.Showsymbols1.DoClick()
  end
end

mv.miSetBookmark0.OnClick=nosymbolbookmark
mv.miSetBookmark1.OnClick=nosymbolbookmark
mv.miSetBookmark2.OnClick=nosymbolbookmark
mv.miSetBookmark3.OnClick=nosymbolbookmark
mv.miSetBookmark4.OnClick=nosymbolbookmark
mv.miSetBookmark5.OnClick=nosymbolbookmark
mv.miSetBookmark6.OnClick=nosymbolbookmark
mv.miSetBookmark7.OnClick=nosymbolbookmark
mv.miSetBookmark8.OnClick=nosymbolbookmark
mv.miSetBookmark9.OnClick=nosymbolbookmark
```

**Comment by advanceddeveloper** [comment] 2018-05-27 19:40
@cheat-engine 

Thanks. It works for me.

The only issue, though, is that I don't see module names in bookmark list (when they are bookmarked), but I think it is not so big problem.

If I understood it correctly, cheat engine stores bookmarks as strings and resolves them every time user navigates to them. Wouldn't it be easier to store bookmarks internally as hexadecimal addresses, but display them as strings? It would resolve this issue completely (actual address would be stored in bookmarks, but GetHandleVerifier will be displayed in bookmarks list, so no confusion would occur) and also it would improve performance. If you think it is worth improving it, let me know, otherwise feel free to close this issue.

**Comment by advanceddeveloper** [comment] 2018-05-27 19:47
.

**Comment by cheat-engine** [comment] 2018-05-28 04:42
CE stores it as strings so when the game crashes and dll's load at randomized locations the bookmarks will be at the correct new location.

**Closed** 2019-07-22 22:47 UTC
