### ISSUE TITLE
Suggestion to pick an LGPL or GPL license

### ISSUE THREAD

**Issue by Gregaras** [cheat-engine/cheat-engine#2009] opened 2022-01-21 11:16 UTC
Q: Why open source license such as LGPL or GPL or AGPL or MIT or BSD or Apache (or other such licenses)?
A: Because I believe the project will still be under development even If the original maintainers don't develop it If you choose one of these licenses.

Q: Why open source copyleft license such as LGPL or GPL or AGPL?
A: Because I believe that these licenses support community effort and not random people effort who pick projects and turn them into proprietary projects. 

Maybe I would suggest LGPL, since backend developers tend to pick that license. GPL (or AGPL) would put certain restrictions for proprietary software developers ([GNU project writes](https://www.gnu.org/licenses/why-not-lgpl) that proprietary software developers would pick another library for their projects because of these restrictions, although I suppose Cheat Engine is unique, don't know actually).

**Comment by Symbai** [comment] 2022-01-21 13:58
Dupe of #60 also see Dark Byte's answer https://github.com/cheat-engine/cheat-engine/issues/60#issuecomment-467317576

**Comment by Gregaras** [comment] 2022-01-21 14:10
> Dupe of #60 also see Dark Byte's answer [#60 (comment)](https://github.com/cheat-engine/cheat-engine/issues/60#issuecomment-467317576)

If you want (If it is possible) you can delete this issue, I can comment in an issue you linked.

**Closed** 2022-01-21 14:26 UTC
